name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
    

jobs:
 
     

  publish-gpr:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@pavankumar636'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACAKGE_T}}
