
name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
    - run: node -v
    - run: npm install 
    - run: npm run build 
#     - run: npm test
    - run: ls
    - run: ls build
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
    
    
