name: Node.js package with npm reg  #name of the workflow

on:
   push:
    branches: [ main ] 

#    release:
#     types: [created]
   workflow_dispatch:    

jobs:
 
  publish-Github-packages:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Github code Checkout
        uses: actions/checkout@v2  #This will help in Checking Out the code and running it in workflow.
        
      - name: Setting and preapring for package creation.
        uses: actions/setup-node@v2 #This action helps with building node packages
        with:
          node-version: 16
          registry-url:  https://registry.npmjs.org
          
          
      - name: Installing Node pacakges and Building package.
        run: npm install  #Install's and get's all packages from package.json file
        run: ls
        
      - name: Publising Package in to Github Package Repositroy 
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGE}} 
          # PAT token should be used and with permissions requried for the token and stored in secrets.
